var i18n = jQuery.extend({}, i18n || {}, { //edits from original by Jim Coltz 2011-12-09
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Sun",
            "mon": "Mon",
            "tue": "Tue",
            "wed": "Wed",
            "thu": "Thu",
            "fri": "Fri",
            "sat": "Sat",
            "jan": "Jan",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Apr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Aug",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dec"
        },
        "no_implemented": "Not implemented yet",
        "to_date_view": "Click to view the current date",
        "i_undefined": "",
        "allday_event": "All day event",
        "repeat_event": "Repeat event",
        "time": "Time",
        "event": "Event",
        "location": "Location",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "New event",
        "confirm_delete_event": "Do you confirm you want to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contain ($ or jQuery<>)",
        "view_no_ready": "View is not ready",
        "example": "e.g., Meeting in room 107",
        "content": "Subject/Event",
        "create_event": "Create event",
        "update_detail": "Edit details",
        "click_to_detail": "View details",
        "i_delete": "Delete",
        "day_plural": "days",
        "others": "Others",
        "item": ""
    }
});
